<a href="https://colab.research.google.com/github/Rhaamm/Linear-Algebra-58019/blob/main/FinalExam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1. Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have? (30 points)

In [24]:
eq1 = np.array([[1,1,1], [1,0,4], [0,0,5]])
eq2 = np.array([[89], [89], [95]])
amt = np.linalg.inv(eq1).dot(eq2)
print(amt)

[[13.]
 [57.]
 [19.]]


Problem 2. Solve each system: (30 points)

In [25]:
A = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
print(A)
B = np.array([[5],[15],[-20]])
print (B)

# compute the pseudo inverse of A
# computationally intensive for large problems
Apinv = np.linalg.pinv(A)

# apply the pseudo-inverse to the rhs
# vector to obtain the `solution'
x = Apinv.dot(B)
print(x)

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]
[[  5]
 [ 15]
 [-20]]
[[ 1.36363636]
 [-0.45454545]
 [ 0.45454545]]


Problem 3. Consider The Matrix (40points)

In [26]:
import numpy as np
from numpy.linalg import eig

A = np.array([[8, 5, -6], [-12, -9, 12], [-3, -3, 5]])
print(A,"\n")
w,v = np.linalg.eig(A)
print("Eigenvalue/s:\n",w.round(),"\n")
print("Eigenvector/s:\n",v.round())

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]] 

Eigenvalue/s:
 [-1.  3.  2.] 

Eigenvector/s:
 [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
