<a href="https://colab.research.google.com/github/Rhaamm/Linear-Algebra-58019/blob/main/MidtermExam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Midterm Examination

#Question 1

In [8]:
square_matrix = np.identity(5)
print(f'Square Matrix whose length is 5: \n{square_matrix}')

Square Matrix whose length is 5: 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#Question 2

In [9]:
upper_triangular_matrix = np.array([[1,2,3],
                                    [0,3,1],
                                    [0,0,5]])
print(upper_triangular_matrix)

[[1 2 3]
 [0 3 1]
 [0 0 5]]


#Question 3

In [11]:
#Creates a square matrix which is symmetrical
square_matrix = np.array ([[1,2,3,4,5],
                           [2,1,2,3,4],
                           [3,2,1,2,3],
                           [4,3,2,1,2],
                           [5,4,3,2,1]])
#Prints a square matrix which is a symmetrical
print ('A square matrix which is symmetrical')
print (square_matrix)

A square matrix which is symmetrical
[[1 2 3 4 5]
 [2 1 2 3 4]
 [3 2 1 2 3]
 [4 3 2 1 2]
 [5 4 3 2 1]]


#Question 4

In [6]:
import numpy as np

C = np.array ([[1,2,3],[2,3,3],[3,4,-2]])

invC = np.linalg.inv(C) #Inverse of Matrix C

print(invC)

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


#Question 5

In [5]:
import numpy as np

C = np.array ([[1,2,3],[2,3,3],[3,4,-2]])

detOfC = np.linalg.det(C)

print("Determinant of the given matrix in Question 4:")
print(int(detOfC))

Determinant of the given matrix in Question 4:
5


#Question 6

In [7]:
import numpy as np

Equations = np.array([[5,4,1],
                      [10,9,4],
                      [10,13,15]])

Constants = np.array([[[3.4],
                       [8.8],
                       [19.2]]])

roots = np.linalg.inv(Equations) @ Constants

print(roots)

[[[0.2]
  [0.4]
  [0.8]]]
