<a href="https://colab.research.google.com/github/Rhaamm/Linear-Algebra-58019/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
A = np.array([[-5,0],[4,1]]) 
B = np.array([[6,-3],[2,3]]) 

sum = np.add(A,B)

print("Sum of A and B:")
print(sum)

Sum of A and B:
[[ 1 -3]
 [ 6  4]]


In [2]:
import numpy as np
A = np.array([[-5,0],[4,1]]) 
B = np.array([[6,-3],[2,3]]) 

difference1 = np.subtract(A,B)
print("\nDifference of A and B:")
print(difference1)


Difference of A and B:
[[-11   3]
 [  2  -2]]


In [3]:
import numpy as np
A = np.array([[-5,0],[4,1]]) 
B = np.array([[6,-3],[2,3]]) 

difference2 = np.subtract(B,A)
print("\nDifference of B and A:")
print(difference2)


Difference of B and A:
[[11 -3]
 [-2  2]]
